name: build

permissions: read-all

on:
  push:
  pull_request:
  schedule:
  - cron: "46 3 * * 0"  # Run at a random time weekly

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup conda and dependencies
      run: |
        util/setup_ci.sh ${{ matrix.python-version }}
    - name: Test
      run: |
        eval "$(conda shell.bash hook)"
        conda activate python${{ matrix.python-version }}
        cd test
        # Run a quick subset of all tests
        python test.py Tests.test_mmcif
